#!/usr/bin/env python

import sys

from rqt_mlp.mlp import Mlp
from rqt_gui.main import Main

plugin = 'rqt_mlp.mlp.Mlp'
main = Main(filename=plugin)
sys.exit(main.main(standalone=plugin, plugin_argument_provider=Mlp.add_arguments))
