#!/usr/bin/env python

import sys

from rqt_mybag.mybag import MyBag
from rqt_gui.main import Main

plugin = 'rqt_mybag.mybag.MyBag'
main = Main(filename=plugin)
sys.exit(main.main(standalone=plugin, plugin_argument_provider=MyBag.add_arguments))
